name: campusquest
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: 0.20.2
  open_file: ^3.3.2
  flutter_staggered_animations: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  fl_chart: ^0.65.0
  csv: ^5.0.1
  file_picker: ^8.0.0
  open_file: ^3.0.3
  shimmer: ^3.0.0
  http: ^1.3.0
  google_fonts: ^6.2.1
  flutter_animate: ^1.0.0
  cached_network_image: ^3.2.0
  path_provider: ^2.1.0
  pdf: ^3.11.3
  printing: ^5.14.2
  flutter_local_notifications: ^17.0.0
  universal_html: ^2.2.4
  uuid: ^3.0.4
  flutter_native_splash: ^2.3.1
  permission_handler: ^11.3.1
  dio: ^5.3.0
  path: ^1.9.0
  flutter_pdfview: ^1.4.0
  photo_view: ^0.15.0
  open_file_manager: ^1.1.1
  device_preview: ^1.2.0
  url_launcher: ^6.0.6
  flutter_file_dialog: ^3.0.2
  supabase_flutter: ^2.8.4
  image_picker: ^0.8.4+4
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/students.png
    - assets/google_logo.png
    - assets/login_illustration.png
    - assets/signup_illustration.png
    - assets/vr_logo.png
    - assets/logocq.png
    - assets/admin.png
    - assets/Untitled design.png
    - assets/campusquest.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/campusquest.png"
  remove_alpha_ios: true
